grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "issuer"
    hosts:
      - grafana.gutama-devops-portfolio.link
    tls:
      - secretName: grafana-tls
        hosts:
           - grafana.gutama-devops-portfolio.link